-- Intentionally left as a no-op.
--
-- This migration version exists in remote Supabase migration history, so the
-- file must remain present locally for `supabase db push` history checks.
-- New leagues generate their draft pools through the production backend path;
-- there are no existing production leagues to backfill.
